import chokidar from 'chokidar';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const memoryManagerPath = path.resolve(__dirname, '../../scripts/memory-manager.js');

let MemoryManager = null;
try {
    const mm = await import(memoryManagerPath);
    MemoryManager = mm.MemoryManager || mm.default;
} catch (e) {
    console.error('Falha ao carregar MemoryManager:', e);
}

class MemoryWatcher {
    constructor() {
        this.watcher = null;
        this.eventCount = 0;
        this.maxEventsBeforeSummary = 20;
        this.mm = MemoryManager ? new MemoryManager() : null;
    }

    start() {
        if (!this.mm) {
            console.error('MemoryManager não disponível. Watcher não será iniciado.');
            return;
        }

        console.log('👁️ Iniciando Memory Watcher...');
        
        // Monitorar arquivos
        this.watcher = chokidar.watch(path.resolve(__dirname, '../../../'), {
            ignored: /(^|[\/\\])\..|node_modules/, // ignore dotfiles and node_modules
            persistent: true,
            ignoreInitial: true,
        });

        this.watcher
            .on('add', (filePath) => this.logEvent('file_added', filePath))
            .on('change', (filePath) => this.logEvent('file_changed', filePath))
            .on('unlink', (filePath) => this.logEvent('file_deleted', filePath));

        console.log('✅ Watcher configurado e monitorando arquivos.');
    }

    stop() {
        if (this.watcher) {
            this.watcher.close();
            console.log('🛑 Memory Watcher parado.');
        }
    }

    async logEvent(type, detail) {
        const relativePath = path.relative(path.resolve(__dirname, '../../../'), detail);
        const content = `[Watcher] Evento: ${type} no arquivo: ${relativePath}`;
        
        try {
            if (this.mm && typeof this.mm.saveMemory === 'function') {
                this.mm.saveMemory(content, { agent: 'watcher', type: 'file_event', autoGenerated: true });
                this.eventCount++;
                
                if (this.eventCount >= this.maxEventsBeforeSummary) {
                    this.triggerSummary();
                    this.eventCount = 0;
                }
            }
        } catch (error) {
            console.error('Erro ao salvar no MemoryManager:', error);
        }
    }

    triggerSummary() {
        console.log('🔄 Disparando summarização automática...');
        // Em um sistema real, chamaria o memory-summarizer.js aqui.
        try {
            import('./memory-summarizer.js').then((module) => {
                if (module.default && typeof module.default.summarize === 'function') {
                    module.default.summarize();
                }
            });
        } catch (e) {
            console.error('Erro ao invocar memory-summarizer:', e);
        }
    }
}

export default MemoryWatcher;
